---
- name: Validate nginx before reload
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: reload_nginx

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx.service
    state: reloaded
  listen: reload_nginx
  when: not ansible_check_mode
